version: '2.1'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-management-alpine
    networks:
      - notifications-network
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_ERLANG_COOKIE=alpha-cookies
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

networks:
  notifications-network:
    driver: bridge
